### ISSUE TITLE
rmsdmatrix setting in `mdref-glycans-sf400x16.toml` confirmation.

### ISSUE THREAD

**Issue by alchemistcai** [haddocking/protein-glycans#1]
I found that 1C1L contains a disaccharide but in its `mdref-glycans-sf400x16.toml`>[rmsdmatrix]>resdic_B = [1,2,3,4,5,6,7].

And all `mdref-glycans-sf400x16.toml`s ' resdic_B is same.

I realize that in the benchmark all the glycans' length is 2~7.

So if resdic_* has  redundant residues indice,will Haddock3 ignore those automaticly?This behavior is handy but not shown in it's [document](https://www.bonvinlab.org/haddock3/modules/analysis/haddock.modules.analysis.rmsdmatrix.html#module-haddock.modules.analysis.rmsdmatrix).I need a confirmation.

Also,`unbound_ens_vdw_tip-ap_clust.toml` use `rmsdmatrix` module while there is an `ilrmsdmatrix` module.In the `report.html`,i-RMSD/L-RMSD/iL-RMSD are calculated all.Will it be different if I use rmsdmatirx or ilrmsdmatrix?

**Comment by mgiulini** [comment]
Hi @alchemistcai , good questions! Indeed `rmsdmatrix` ignores the non-existing residues in the selection. Knowing that the longest glycan in our benchmark is 7 monosaccharides long we used the same list everywhere. Indeed it makes sense to add this to the documentation, thanks!

as for the `ilrmsdmatrix` module, can you please tell me where you see it?

the good advantage of the `ilrmsdmatrix` module is that you don't have to specify any residue set: the interface receptor residues will be selected automatically among those that are at the interface across all the models. Of course, if you know more or less where the protein interface will be, the `rmsdmatrix` will allow you to be more precise by specifying only those residues for the RMSD calculation. If the docking is driven by good information, the results should not be dramatically different.

In the report.html you see all the RMSD quantities indeed: these correspond to the distance from the reference structure (if provided) or from the best scoring model (if no reference is provided).

**Comment by alchemistcai** [comment]
Thanks for your answer!

When I search rmsdmatrix in the official document,ilrmsdmatrix is just under rmsdmatrix,they are under same directory.Also in haddock3's examples,I found some cfg files use ilrmsdmatrix instead of rmsdmatrix.

So in summary,ilrmsdmatrix is automatic and handy for benchmark tests,while rmsdmatrix needs manual configuration but is more suitable for unknown complex docking.

**Comment by mgiulini** [comment]
`rmsdmatrix` is indeed more suitable if you are sure about your interface information. happy docking!
